import json
from pathlib import Path

import pytest

from hogflow.core import InputDataError
from hogflow.data.models import (
    CameraStabilityLabel,
    ManualReviewMetadata,
    SuitabilityLabel,
    SuitabilitySettings,
    VideoFileMetadata,
)
from hogflow.data.validation import (
    classify_suitability,
    discover_video_files,
    load_clip_manifest,
    load_review_sidecar,
    review_sidecar_path,
)


def _review(**overrides: object) -> ManualReviewMetadata:
    values: dict[str, object] = {
        "authorized_for_project": True,
        "source_type": "synthetic",
        "source_reference": "local fixture",
        "license_or_permission_notes": "generated by tests",
        "camera_static_confirmed": True,
        "clear_passage_confirmed": True,
        "predominant_direction_confirmed": True,
        "counting_line_possible": True,
        "intended_use": ("detection", "tracking", "counting"),
        "reviewer_notes": "",
    }
    values.update(overrides)
    return ManualReviewMetadata(**values)  # type: ignore[arg-type]


def _metadata(**overrides: object) -> VideoFileMetadata:
    values: dict[str, object] = {
        "relative_path": "clip.avi",
        "file_size_bytes": 100,
        "container_extension": ".avi",
        "duration_seconds": 10.0,
        "fps": 10.0,
        "frame_count": 100,
        "width": 100,
        "height": 80,
        "codec": "MJPG",
        "readable": True,
        "validation_errors": (),
        "stability_label": CameraStabilityLabel.LIKELY_STATIC,
    }
    values.update(overrides)
    return VideoFileMetadata(**values)  # type: ignore[arg-type]


def test_empty_dataset_directory_is_supported(tmp_path: Path) -> None:
    assert discover_video_files(tmp_path) == ()


def test_discovery_is_recursive_deterministic_and_filters_artifacts(tmp_path: Path) -> None:
    (tmp_path / "z.MP4").write_bytes(b"")
    (tmp_path / "a.mov").write_bytes(b"")
    (tmp_path / "nested").mkdir()
    (tmp_path / "nested" / "b.webm").write_bytes(b"")
    (tmp_path / "nested" / "notes.txt").write_text("not video", encoding="utf-8")
    (tmp_path / ".hidden").mkdir()
    (tmp_path / ".hidden" / "hidden.mp4").write_bytes(b"")
    (tmp_path / "thumbnails").mkdir()
    (tmp_path / "thumbnails" / "generated.mp4").write_bytes(b"")
    (tmp_path / "clip.partial.avi").write_bytes(b"")

    assert discover_video_files(tmp_path) == (
        Path("a.mov"),
        Path("nested/b.webm"),
        Path("z.MP4"),
    )


def test_discovery_rejects_missing_or_non_directory_root(tmp_path: Path) -> None:
    with pytest.raises(InputDataError):
        discover_video_files(tmp_path / "missing")
    file_path = tmp_path / "file"
    file_path.write_text("x", encoding="utf-8")
    with pytest.raises(InputDataError):
        discover_video_files(file_path)


def test_review_sidecar_path_preserves_full_video_filename() -> None:
    assert review_sidecar_path("clip.mp4") == Path("clip.mp4.review.json")


def test_review_sidecar_parses_required_fields(tmp_path: Path) -> None:
    path = tmp_path / "clip.avi.review.json"
    path.write_text(
        json.dumps(
            {
                "authorized_for_project": True,
                "source_type": "licensed",
                "source_reference": "license record 1",
                "license_or_permission_notes": "reuse permitted for research",
                "camera_static_confirmed": True,
                "clear_passage_confirmed": False,
                "predominant_direction_confirmed": None,
                "counting_line_possible": None,
                "intended_use": ["detection", "tracking"],
                "reviewer_notes": "manual review incomplete",
            }
        ),
        encoding="utf-8",
    )

    review = load_review_sidecar(path)

    assert review.authorized_for_project is True
    assert review.intended_use == ("detection", "tracking")
    assert review.clear_passage_confirmed is False


def test_review_sidecar_rejects_missing_extra_and_invalid_json(tmp_path: Path) -> None:
    missing_path = tmp_path / "missing.json"
    missing_path.write_text("{}", encoding="utf-8")
    with pytest.raises(InputDataError, match="missing fields"):
        load_review_sidecar(missing_path)

    invalid_path = tmp_path / "invalid.json"
    invalid_path.write_text("{", encoding="utf-8")
    with pytest.raises(InputDataError, match="not valid"):
        load_review_sidecar(invalid_path)


def test_clip_manifest_parses_boundaries_and_rejects_invalid_range(tmp_path: Path) -> None:
    path = tmp_path / "manifest.json"
    entry = {
        "original_source_reference": "authorized source",
        "clip_filename": "clips/clip-001.mp4",
        "start_time_seconds": 5.0,
        "end_time_seconds": 10.0,
        "reason_selected": "static interval",
        "camera_appears_static": True,
        "notes": "",
    }
    path.write_text(json.dumps({"clips": [entry]}), encoding="utf-8")
    assert load_clip_manifest(path)[0].clip_filename == "clips/clip-001.mp4"

    entry["end_time_seconds"] = 5.0
    path.write_text(json.dumps({"clips": [entry]}), encoding="utf-8")
    with pytest.raises(InputDataError, match="greater"):
        load_clip_manifest(path)


def test_counting_candidate_requires_authorization_and_all_manual_confirmations() -> None:
    labels = classify_suitability(_metadata(), _review(), SuitabilitySettings())

    assert labels == (
        SuitabilityLabel.DETECTION_CANDIDATE,
        SuitabilityLabel.TRACKING_CANDIDATE,
        SuitabilityLabel.COUNTING_CANDIDATE,
    )

    incomplete = classify_suitability(
        _metadata(),
        _review(counting_line_possible=None),
        SuitabilitySettings(),
    )
    assert SuitabilityLabel.COUNTING_CANDIDATE not in incomplete
    assert SuitabilityLabel.NEEDS_MANUAL_REVIEW in incomplete

    unauthorized = classify_suitability(_metadata(), None, SuitabilitySettings())
    assert unauthorized == (SuitabilityLabel.NEEDS_MANUAL_REVIEW,)


def test_moving_camera_can_be_a_stress_candidate_but_not_tracking_candidate() -> None:
    labels = classify_suitability(
        _metadata(stability_label=CameraStabilityLabel.MOVING_CAMERA),
        _review(camera_static_confirmed=False),
        SuitabilitySettings(),
    )

    assert SuitabilityLabel.DETECTION_CANDIDATE in labels
    assert SuitabilityLabel.TRACKING_CANDIDATE not in labels
    assert SuitabilityLabel.STRESS_TEST_CANDIDATE in labels
    assert SuitabilityLabel.NEEDS_MANUAL_REVIEW in labels


def test_short_or_invalid_video_is_not_a_detection_candidate() -> None:
    short = classify_suitability(
        _metadata(duration_seconds=1.0),
        _review(),
        SuitabilitySettings(),
    )
    invalid = classify_suitability(
        _metadata(readable=False),
        _review(),
        SuitabilitySettings(),
    )

    assert short == (SuitabilityLabel.NEEDS_MANUAL_REVIEW,)
    assert invalid == (SuitabilityLabel.NEEDS_MANUAL_REVIEW,)
