"""Framework-neutral autonomous counting calibration contracts."""

from hogflow.calibration.engine import (
    AutonomousCalibrationEngine,
    AutonomousCalibrationSettings,
    consistency_confidence,
    detector_perturbation_agreement,
    estimate_corridor,
    estimate_dominant_direction,
    evaluate_candidate_tracks,
    generate_line_candidates,
    line_band_agreement,
    relative_spread,
    select_eligible_trajectories,
)
from hogflow.calibration.models import (
    AutonomousCalibrationResult,
    CalibrationConfidence,
    CalibrationStatus,
    CorridorEstimate,
    CountFamilyMetrics,
    CountingGeometryConfiguration,
    DirectionVector,
    LineCandidate,
    LineCandidateMetrics,
    TrajectoryObservation,
    TrajectorySummary,
)
from hogflow.calibration.orchestration import (
    AUTONOMOUS_CALIBRATION_ALGORITHM_VERSION,
    AutonomousDemoConfiguration,
    AutonomousDemoResult,
    run_autonomous_demo,
)
from hogflow.calibration.video_selection import (
    AutonomousCandidateSuitability,
    AutonomousVideoSelection,
    select_autonomous_demo_candidate,
)

__all__ = [
    "AUTONOMOUS_CALIBRATION_ALGORITHM_VERSION",
    "AutonomousCalibrationResult",
    "AutonomousCalibrationEngine",
    "AutonomousCalibrationSettings",
    "AutonomousCandidateSuitability",
    "AutonomousVideoSelection",
    "AutonomousDemoConfiguration",
    "AutonomousDemoResult",
    "consistency_confidence",
    "detector_perturbation_agreement",
    "CalibrationConfidence",
    "CalibrationStatus",
    "CountFamilyMetrics",
    "CorridorEstimate",
    "CountingGeometryConfiguration",
    "DirectionVector",
    "LineCandidate",
    "LineCandidateMetrics",
    "TrajectoryObservation",
    "TrajectorySummary",
    "estimate_corridor",
    "estimate_dominant_direction",
    "evaluate_candidate_tracks",
    "generate_line_candidates",
    "line_band_agreement",
    "relative_spread",
    "select_eligible_trajectories",
    "select_autonomous_demo_candidate",
    "run_autonomous_demo",
]
